
indices_dispo <- data.frame(user=NA,indice=NA)[0,]
# indices_dispo[nrow(indices_dispo)+1,] <-  list("Baal","A")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Baal","L")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Baal","M")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Baal","S")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Baal","G") # Nouveau 
indices_dispo[nrow(indices_dispo)+1,] <-  list("Dominique","I")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Dominique","D")
# indices_dispo[nrow(indices_dispo)+1,] <-  list("Dominique","M")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Dominique","C")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Dominique","H") # Nouveau 
indices_dispo[nrow(indices_dispo)+1,] <-  list("Yves","J")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Yves","L")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Yves","N")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Yves","F") # Nouveau 
indices_dispo[nrow(indices_dispo)+1,] <-  list("Valefor","A")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Valefor","B")
# indices_dispo[nrow(indices_dispo)+1,] <-  list("Valefor","C")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Valefor","P")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Valefor","G") # Nouveau 
indices_dispo[nrow(indices_dispo)+1,] <-  list("Andréalphus","I")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Andréalphus","D")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Andréalphus","N")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Andréalphus","R")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Andréalphus","H") # Nouveau 
indices_dispo[nrow(indices_dispo)+1,] <-  list("Jésus","M")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Jésus","O")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Jésus","P")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Jésus","E") # Nouveau 
indices_dispo[nrow(indices_dispo)+1,] <-  list("Blandine","J")
# indices_dispo[nrow(indices_dispo)+1,] <-  list("Blandine","L")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Blandine","Q")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Blandine","R")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Blandine","S")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Malphas","A")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Malphas","K")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Malphas","C")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Malphas","O")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Malphas","F") # Nouveau 
indices_dispo[nrow(indices_dispo)+1,] <-  list("Crocell","K")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Crocell","B")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Crocell","Q")
indices_dispo[nrow(indices_dispo)+1,] <-  list("Crocell","E") # Nouveau 

# table(indices_dispo$indice)
# table(indices_dispo$user)

info_indices <- data.frame(indice=NA,titre=NA,variation=NA,texte=NA)[0,]

# Etudes scientifiques menées par l'archange yves : baisse de puissance des archanges et des princes démons
info_indices[nrow(info_indices)+1,] <-  list("A","Etudes scientifiques menées par l'archange Yves",1,"Janus, Archange du Vent, aurait osé décliné l'invitation à la soirée de ce soir, pour convenable personnelle.")
info_indices[nrow(info_indices)+1,] <-  list("A","Etudes scientifiques menées par l'archange Yves",2,"Yves, Archange des Sources, a mené récemment en compagnie de Jean, Archange de la Foudre, des expériences scientifiques mesurant l’évolution de la puissance des Archanges et des Princes Démons. Votre équipe n’a pu obtenir communication des résultats.

Remarque de votre chargé de mission :
Nous avons tenté d’obtenir ces documents,sans succès. Nous pensons que les résultats sont inquiétants — d’une manière ou d’un autre — et qu’ils ont été volontairement dissimulés.")
info_indices[nrow(info_indices)+1,] <-  list("A","Etudes scientifiques menées par l'archange Yves",3,"Yves, Archange des Sources, a mené récemment en compagnie de Jean, Archange de la Foudre, des expériences scientifiques mesurant l’évolution de la puissance des Archanges et des Princes Démons.

Les résultats ont été volontairement dissimulés, mais après de nombreux efforts et quelques pots de vin, nous avons réussi à en obtenir une copie. Il semblerait que la puissance des Archanges et des Princes Démons ait baissé de manière régulière dès que Dieu partait en exploration dans des univers parallèles. Leur puissance remontait dès que Dieu refaisait son apparition au Paradis.

Remarque de votre chargé de mission :
On dirait que l’éloignement de Dieu affaiblit ses créations, Anges, Démons, Archanges et Princes Démons. Si vous me permettez un commentaire personnel, monseigneur, cela me semble inquiétant... Que va-t-il advenir de nous maintenant que Dieu a complètement disparu ?Nous vous prévenons cependant que les recherches pourront prendre un certain temps...
Notre puissance, à nous autres créations de Dieu, continue-t-elle à baisser ? Sommes-nous condamnés ? Voulez-vous que nous enquêtions sur le sujet ? 
(Note au joueur : L'enquête est maintenant disponible : 'Les expériences de Jean')")

# Les expériences de Jean
info_indices[nrow(info_indices)+1,] <-  list("AA","Les expériences de Jean",1,"Le Prince Démon Andréalphus aurait pris, au cours des années 80, la forme d’Edith Cresson afin de séduire Mitterrand. Cette information n’est pas confirmée. Edith Cresson n’est pas très sexy, mais la vie de Mitterrand recèle bien d’autres mystères.")
info_indices[nrow(info_indices)+1,] <-  list("AA","Les expériences de Jean",2,"Il semblerait que Jean, Archange de la Foudre (Jean est un grand scientifique — il n’est pas présent à cette soirée), ait conduit ces derniers jours, depuis la mort de Dieu, une étude sur la puissance des Archanges et des Princes Démons pour voir si elle avait été affectée par la disparition de Dieu. Les résultats, qui ont été volontairement dissimulés, sont hélas plus que probants. Oui, la puissance des Archanges et des Princes Démons (ainsi bien sûr que celle de leurs serviteurs, Anges et Démons) baisse de manière régulière et sensible depuis la mort de Dieu. La source de puissance s’est tarie. A ce rythme là, dans un siècle, Anges, Démons, Archanges et Princes Démons auront tous disparu.
Remarques de votre chargé de mission :
Nous espérons de tout cœur que l Archange Jean se trompe... bien que ce ne soit guère probable.
Nous avons également découvert qu’Yves, l’Archange des Sources, avait mené avant la mort de Dieu une enquête sur le sujet pour découvrir ce qui arriverait «au cas où» Dieu disparaîtrait... et avait anticipé ces résultats. L Archange Yves a eu, semble-t-il, de nombreuses discussions avec
Jésus sur ce thème. Jésus semblait très intéressé et a vérifié plusieurs fois les résultats de l’expérience.")
info_indices[nrow(info_indices)+1,] <-  list("AA","Les expériences de Jean",3,"Il semblerait que Jean, Archange de la Foudre (Jean est un grand scientifique - il n’est pas présent à cette soirée), ait conduit ces derniers jours, depuis la mort de Dieu, une étude sur la puissance des Archanges et des Princes Démons pour voir si elle avait été affectée par la disparition de Dieu. Les résultats, qui ont été volontairement dissimulés, sont hélas plus que probants. Oui, la puissance des Archanges et des Princes Démons (ainsi bien sûr que celle de leurs serviteurs, Anges et Démons) baisse de manière régulière et sensible depuis la mort de Dieu. La source de puissance s’est tarie. A ce rythme là, dans un siècle, Anges, Démons, Archanges et Princes Démons auront tous disparu.
Remarques de votre chargé de mission :
Nous espérons de tout cœur que l Archange jean se trompe... bien que ce ne soit guère probable. Nous avons également découvert qu’Yves, l’Archange des Sources, avait mené avant la mort de Dieu une enquête sur le sujet pour découvrir ce qui arriverait «au cas où» Dieu disparaîtrait... et avait anticipé ces résultats. L’Archange Yves a eu, semble-t-il, de nombreuses discussions avec Jésus sur ce thème. Jésus semblait très intéressé et a vérifié plusieurs fois les résultats de l’expérience.
Permettez nous d’ajouter deux informations intéressantes :
•	L’Archange Jean avait proposé à ¡Archange Yves de participer avec lui aux analyses... après tout, Yves avait bossé sur le sujet le premier. Mais Yves a refusé, semblant ne même pas comprendre de quoi F Archange Jean était en train de parler. Jean a même fait remarquer qu’Yves semblait complètement changé de caractère depuis la mort de Dieu, comme si celle-ci l’avait profondément choqué. Il a affirmé «ne plus le reconnaître».
•	Une information de dernière minute : il semble que les tous derniers résultats d’analyse de Jean — des mesures qu’il vient d’effectuer pendant ce conseil sur les Archanges et les Princes Démons réunis ici ce soir — contredisent complètement ses premiers résultats. L’Archange a affirmé qu’il allait refaire les analyses avant de se prononcer, mais ces résultats incroyables témoigneraient, uniquement depuis le début de ce conseil, d’une augmentation surprenante et inexpliquée de leur puissance. Ces résultats sont en cours de confirmation.
•	Une autre information de dernière minute, qui n’a hélas pas de rapport avec l'enquête demandée mais que nous avons découverte en parlant avec l’Archange Jean : il semble que plusieurs témoins aient affirmé avoir découvert, après la mort de: Dieu, des taches de sang sous la fameuse manette devant le laboratoire.")

# Apparitions étranges à the Scientific and Magic Institute, San Franscico, USA
info_indices[nrow(info_indices)+1,] <-  list("B","Apparitions étranges à the Scientific and Magic Institute, San Franscico, USA",1,"Une kermesse en l’honneur des Démons roumains femelles unijambistes à la retraite sera organisée en Enfer le 28 septembre 2003 au soir, à 22h35, dans la grande salle de bal.")
info_indices[nrow(info_indices)+1,] <-  list("B","Apparitions étranges à the Scientific and Magic Institute, San Franscico, USA",2,"Un scientifique américain de grand renom, James David Merreves, a affirmé à la presse avoir reçu à plusieurs reprises la visite de trois êtres mystérieux, deux Archis-démons et un Archi-ange», selon ses propres termes.
Ces mystérieux visiteurs l’auraient interrogé à plusieurs reprises, pendant de longues heures, sur la manière dont il était possible d’allier technologie moderne, énergie angélique et énergie démoniaque afin de créer, à partir d’un corps humain mort, un être de flammes sur puissant, débordant de pouvoir. James David Merreves affirme avoir travaillé sur le sujet des jours et des nuits, sans manger ni dormir, pour obéir à ces apparitions.
Il leur aurait ensuite livré une théorie qui leur aurait donné satisfaction. Après ces révélations, James David Merreves a été interné à la demande de sa femme pour «délire paranoïaque». Il est aujourd’hui sous camisole chimique.")
info_indices[nrow(info_indices)+1,] <-  list("B","Apparitions étranges à the Scientific and Magic Institute, San Franscico, USA",3,"Un scientifique américain de grand renom, James David Merreves, a affirmé à la presse avoir reçu à plusieurs reprises la visite de trois êtres mystérieux «deux Archis-démons et un Archi-ange», selon ses propres termes. Ces mystérieux visiteurs l’auraient interrogé à plusieurs reprises, pendant de longues heures, sur la manière dont il était possible d’allier technologie moderne, énergie angélique et énergie démoniaque afin de créer, à partir d’un corps humain mort, un être de flammes surpuissant, débordant de pouvoir. Le scientifique affirme avoir entendu les apparitions dire qu’elles voulaient créer un «Antéchrist». James David Merreves affirme avoir travaillé sur le sujet des jours et des nuits, sans manger ni dormir, pour obéir à ces apparitions. Il leur aurait ensuite livré une théorie qui leur aurait donné satisfaction. Après ces révélations, James David Merreves a été interné à la demande de sa femme pour «délire paranoïaque». Il est aujourd’hui sous camisole chimique.
Remarques de votre chargé de mission
Nous nous sommes rendus à l’hôpital psychiatrique où était interné James David. Merreves pour l'interroger plus avant sur cette étrange histoire. 
L’homme est complètement fou, mais raconte-t-il n’importe quoi ou a-t-il perdu l’esprit après cette expérience traumatisante... nous l’ignorons. Nous l’avons cuisiné sur ces soi-disant apparitions. James David Merreves nous a raconté que les trois êtres se disputaient souvent sur l’utilité de cet «Antéchrist» qu’ils avaient l’intention de créer.
Il semble que le premier de ces «Archi-démon» voulait utiliser le faux Antéchrist pour déclencher une guerre entre le Paradis et l’Enfer... espérant que chacun des deux partis accuserait l’autre d’avoir créé cette créature monstrueuse.
Le second «Archi-démon», qui était tout le temps masqué, pensait visiblement que l’apparition de l’Antéchrist dégoûterait pour toujours les humains de la religion et de toutes ces créatures. Il espérait ainsi tuer la foi. Et, bizarrement, la troisième apparition, «l’Archi-ange», espérait au contraire que l’apparition de cet Antéchrist relancerait la foi chrétienne en faisant peur aux humains et en les poussant à se repentir de leurs péchés. 
Si vous me permettez un commentaire personnel, monseigneur, j’ajouterais que si cette histoire est véridique, ces trois individus (il s’agit sans doute de deux Princes Démons et d’un Archange) ont gravement enfreint les lois divines et démoniaques. Créer un faux Antéchrist, quelles que soient leurs motivations, est un blasphème aussi bien contre Lucifer que contre Dieu.
Dieu les aurait puni s’il avait appris cette histoire. Peut-être même l’avait-il appris... Ne pensez-vous pas que l’un d’entre eux, pris au piège, aurait pu baisser la manette et «éliminer Dieu» pour éviter un châtiment mérité ? Il ne s'agit là, remarquez-le bien, que pure spéculation.
Voulez-vous que nous enquêtions sur l’identité de ces trois «apparitions» ? Nous vous prévenons cependant que les recherches pourront prendre un certain temps... (Note au joueur : L'enquête est maintenant disponible : 'Les conjures de l’Antechrist'")


# Les conjures de l’Antechrist
info_indices[nrow(info_indices)+1,] <-  list("BB","Les conjures de l’Antechrist",1,"Le tournoi de Roland Garros serait truqué. Laurent, Archange de l’Epée prendrait régulièrement l’apparence d’André Agassi pour y participer.")
info_indices[nrow(info_indices)+1,] <-  list("BB","Les conjures de l’Antechrist",2,"A votre demande, nous avons enquêté sur l’identité des trois apparitions (l’Archi-ange et les deux Princes-démons) qui, semblent-ils, avaient pour intention de créer un Antéchrist. Ont-ils mené à bien leur plan, nous l’ignorons. Nous avons recoupé les témoignages du scientifique interné avec d’autre observations et des enregistrements des allées et venues des Archanges et des Princes Démons datant de cette période. Il semblerait que le premier Prince-démon soit en vérité le Prince Démon Malphas. Nous ignorons encore l’identité dei l’Archi-ange et celle de l’Archi-démon qui est demeuré masqué pendant toute cette période.")
info_indices[nrow(info_indices)+1,] <-  list("BB","Les conjures de l’Antechrist",3,"A votre demande, nous avons enquêté sur l’identité des trois apparitions (l’Archi-ange et les deux Princes-démons) qui, semblent-ils, avaient pour intention de créer un Antéchrist. Ont-ils mené à bien leur plan, nous l’ignorons. Nous avons recoupé les témoignages du scientifique interné avec d’autres observations et des enregistrements des allées et venues des Archanges et des Princes Démons datant de cette période. Il semblerait que le premier Prince-démon soit en vérité le Prince Démon Malphas, et que l’Archi-ange soit l’Archange Dominique. Nous ignorons encore l’identité du Prince-démon qui est demeuré masqué pendant toute cette période.")

# Ragots d’une petite fille
info_indices[nrow(info_indices)+1,] <-  list("C","Ragots d’une petite fille",1,"L’Archange Joseph (non présent à cette soirée) ne porte que des Levi’s 501.")
info_indices[nrow(info_indices)+1,] <-  list("C","Ragots d’une petite fille",2,"Une petite fille innocente, dénommée Maria, recueillie au Ciel par un Ange a affirmé, à la cafétéria du paradis, qu’elle avait des informations «croustillantes» et «inédites» à vendre sur les Archanges. Maria dit quelle traîne sans surveillance dans les couloirs du Paradis sans que personne ne la remarque et affirme avoir ainsi appris des «scoops». Personne ne semble l’avoir prise au sérieux. Selon vos instructions, nous l’avons fait parler... Ces fameux «scoops» ne sont en vérité que deux. Les voici tels quels — nous ne pouvons hélas pas vous confirmer leur véracité :
•	Maria affirme qu’elle a souvent entendu Jésus, le fils de Dieu, avoir des discussions politiques avec l’Archange Yves. Elle dit que dans ces discussions, Jésus déplorait l’état de la terre et de la société humaine et affirmait que l’intégrisme, donc la religion, en était responsable. Il affirmait que la terre se porterait beaucoup mieux si Dieu, Archanges et «Princes Démons » disparaissaient pour toujours afin de laisser les humains à leur destin.
•	Maria affirme avoir vu, il y quelques semaines, Blandin vider une fiole dans la nourriture de Janis.
•	Maria affirme avoir vu, le jour de la mort de Dieu, un Prince Démon avec une hache se balader discrètement au Paradis.")
info_indices[nrow(info_indices)+1,] <-  list("C","Ragots d’une petite fille",3,"Une petite fille innocente, dénommée Maria, recueillie au Ciel par un Ange a affirmé, à la cafétéria du paradis, qu’elle avait des informations «croustillantes» et «inédites» à vendre sur les Archanges. Maria dit quelle traîne sans surveillance dans les couloirs du Paradis sans que personne ne la remarque et affirme avoir ainsi appris des «scoops». Personne ne semble l’avoir prise au sérieux. Selon vos instructions, nous l’avons droguée pour la faire parler. Elle nous a tout révélé. Voici ces fameux «scoops» tels quels — nous ne pouvons hélas pas vous confirmer leur véracité :
•	Maria affirme avoir vu, un jour, l’Archange Janus, Archange des Vents (non présent à cette soirée), s’introduire discrètement dans la bibliothèque de l’Archange Yves et en ressortir quelques minutes plus tard, aussi discrètement.
•	Maria affirme qu’elle a souvent entendu Jésus, le fils de Dieu, avoir des discussions politiques avec l’Archange Yves. Elle dit que dans ces discussions, Jésus déplorait l’état de la terre et de la société humaine et affirmait que l’intégrisme, donc la religion, en était responsable. Il affirmait que la terre se porterait beaucoup mieux si Dieu, Archanges et Princes Démons disparaissaient pour toujours afin de laisser les humains à leur destin.
•	Maria affirme avoir vu, il y quelques semaines, Blandin vider une fiole dans la nourriture de Janis.
•	Maria affirme avoir vu, le jour de la mort de Dieu, un Prince Démon se balader près du laboratoire de Dieu, près de la fameuse manette.

Remarque de votre chargé de mission :
À propos de ce dernier scoop... Ce ragot semble peu vraisemblable : comment un Prince Démon aurait-il pu pénétrer au Paradis ? Toutes les entrées sont gardées. Cependant, si ce témoignage était véridique, il serait d'une extrême importance. Voulez-vous que nous enquêtions plus avant sur ce sujet ? Nous vous prévenons cependant que les recherches pourront prendre un certain temps... 
(Note au joueur : L'enquête est maintenant disponible : 'Un Prince Démon au Paradis'")

# Tâches de sang au Paradis
info_indices[nrow(info_indices)+1,] <-  list("CC","Un Prince Démon au Paradis",1,"L’Archange Michel (non présent à cette soirée) aurait péché par gourmandise en dévorant sans reprendre sa respiration 18 boites de Pim’s orange.")
info_indices[nrow(info_indices)+1,] <-  list("CC","Un Prince Démon au Paradis",2,"Vous nous aviez demandé d’enquêter sur la présence possible d’un Prince Démon dans le couloir près du laboratoire de Dieu (et de la fameuse manette) le jour, justement, de la mort de Dieu. Nous pouvons vous confirmer cette présence. Il s’agit, d’après les témoignages, d’un être rougeoyant, cornu, armé d’une hache. L’être avait l’air furieux.
Par contre, plusieurs témoins ont affirmé avoir découvert, après la mort de Dieu, des tâches de sang sous la fameuse manette.")

info_indices[nrow(info_indices)+1,] <-  list("CC","Un Prince Démon au Paradis",3,"Vous nous aviez demandé d’enquêter sur la présence possible d’un Prince Démon dans le couloir près du laboratoire de Dieu (et de la fameuse manette) le jour, justement, de la mort de Dieu. Nous pouvons vous confirmer cette présence. Il s’agit, d’après les témoignages, d’un être rougeoyant, cornu, armé d’une hache. L’être avait l’air furieux. 
Autre chose, plusieurs témoins ont affirmé avoir découvert, après la mort de Dieu, des taches de sang sous la fameuse manette, ainsi que l’Archange Jésus, blessé à la poitrine et saignant abondamment, regagner à pied ses appartements... cela peu de temps après la mort de Dieu.")


# Alerte sur le continuum spationtemporel
info_indices[nrow(info_indices)+1,] <-  list("D","Alerte sur le continuum spationtemporel",1,"Le 1er juin 1996, il y avait exactement 260 245 Anges au Paradis.")
info_indices[nrow(info_indices)+1,] <-  list("D","Alerte sur le continuum spationtemporel",2,"Les services de Kronos, Prince Démon de l'éternité, ont enregistré des fluctuations extrêmement importantes du Continuum Spatio Temporel ces derniers mois. Il semble qu’un ou des individus d'une grande puissance, sans aucun doute Archanges ou Princes Démons, aient remonté le temps, puis soient revenu à notre époque... Ces voyages dans le temps ont été effectué sans précautions, et sans la permission des services concernés. Il s’agit là d’une faute grave. Dieu seul sait quels dégâts ont pu être infligés au Continuum Spatio Temporel")
info_indices[nrow(info_indices)+1,] <-  list("D","Alerte sur le continuum spationtemporel",3,"Les services de Kronos, Prince Démon de l'éternité, ont enregistré des fluctuations extrêmement importantes du Continuum Spatio Temporel ces derniers mois. Il semble que des individus d'une grande puissance, sans aucun doute Archanges ou Princes Démons, aient remonté le temps, puis soient revenu à notre époque... Les destination temporelles semblent être la préhistoire ainsi une période se situant approximativement entre l’an 30 ou l’an 40 après Jésus-Christ. Ces voyages dans le temps ont été effectués sans précautions, et sans la permission des services concernés. Il s’agit là d’une faute grave. Dieu seul sait quels dégâts ont pu être infligés au Continuum Spatio Temporel. Voulez-vous que nous enquêtions sur les deux destinations ? Nous vous prévenons cependant que les recherches pourront prendre un certain temps...
(Note au joueur : une enquête est maintenant disponible : 'Voyages temporels')")

# Voyages temporels"
info_indices[nrow(info_indices)+1,] <-  list("DD","Voyages temporels",1,"")
info_indices[nrow(info_indices)+1,] <-  list("DD","Voyages temporels",2,"Nous nous sommes renseignés davantage auprès des services de Kronos, concernant ces voyages temporels.
Concernant la période entre 30 et 40 ans après Jésus-Christ, il s'avère qu'il s'agit exactement (tant au niveau du lieu que de la temporalité) de la crucifiction de Jésus. Les services temporels ont déterminé qu'il s'agit d'un Prince Démon.
Concernant la période préhistoirique, ceux ci ont été nombreux dans les deux derniers mois, par un seul indiviu. Les destinations et temporalité laissent à penser que cet individu a cherché à assister à la naissance de l'humanité telle que nous la connaissons (découverte du feu et de l'agriculture par exemple). Les services de Kronos ont été incapable de déterminer s'il s'agissait d'un Archange ou d'un Prince Démon.")
info_indices[nrow(info_indices)+1,] <-  list("DD","Voyages temporels",3,"Nous nous sommes renseignés davantage auprès des services de Kronos, concernant ces voyages temporels.
Concernant la période entre 30 et 40 ans après Jésus-Christ, il s'avère qu'il s'agit exactement (tant au niveau du lieu que de la temporalité) de la crucifiction de Jésus. Les services temporels ont déterminé qu'il s'agit d'un Prince Démon.
Concernant la période préhistoirique, ceux ci ont été nombreux dans les deux derniers mois, par un seul indiviu. Les destinations et temporalité laissent à penser que cet individu a cherché à assister à la naissance de l'humanité telle que nous la connaissons (découverte du feu et de l'agriculture par exemple). Les services de Kronos ont été incapable de déterminer s'il s'agissait d'un Archange ou d'un Prince Démon.
Note concernant cette information :
Il est très étrange que les services de Kronos n'aient pas pu déterminer si l'individu était un Archange ou un Prince Démon. Par le passé, tout ces mouvements ont pu être détectés sans problème.")


# le nouveau virus de l'Archange Guy

info_indices[nrow(info_indices)+1,] <-  list("E","Le nouveau virus de l'Archange Guy",1,"")
info_indices[nrow(info_indices)+1,] <-  list("E","Le nouveau virus de l'Archange Guy",2,"Guy (Archange des guérisseurs, non présent à cette soirée) aurait découvert un nouveau virus : le HBLI-5. Ce virus serait capable d'altérer le cerveau des humains en le rendant moins perméable aux manipulations franches des anges et des démons. Ce virus, s'il était propagé, pourrait semble-t-il atténuer le pouvoir qu'on les entités supérieures sur l'humanité, ce qui est un peu gênant pour votre travail, non ? Surtout que le virus serait très contagieux, et pourrait se propoger via les plantes et les animaux.

Rassurez vous, il semblerait néanmoins que le virus ne puisse affecter que les humains, et encore de manière très très lente à l'échelle humaine (quelques milliers d'années). De plus, Guy n'a absolument pas envie de le déployer, il s'agissait uniquement de recherche.")
info_indices[nrow(info_indices)+1,] <-  list("E","Le nouveau virus de l'Archange Guy",3,"Guy (Archange des guérisseurs, non présent à cette soirée) aurait découvert un nouveau virus : le HBLI-5. Ce virus serait capable d'altérer le cerveau des humains en les rendant moins perméable aux manipulations franches des anges et des démons. Ce virus, s'il était propagé, pourrait semble-t-il atténuer le pouvoir qu'on les entités supérieures sur l'humanité, ce qui est un peu gênant pour votre travail, non ? Surtout que le virus serait très contagieux, et pourrait se propoger via les plantes et les animaux.

Rassurez vous, il semblerait néanmoins que le virus ne puisse affecter que les humains, et encore de manière très très lente à l'échelle humaine (quelques milliers d'années). De plus, Guy n'a absolument pas envie de le déployer, il s'agissait uniquement de recherche.

Par contre, en nous renseignant davantage sur ses travaux, Guy nous a appris qu'un vol a été effectué dans son laboratoire et l'armoire contenant tous les virus a été forcée. Une fiole a été volée, contenant le virus HHLI-5, un virus se propageant de la même manière que le HBLI-5, mais provoquant des accès de folie et une aggressivité accrue.")

# L'intervention de Lucifer en Yougoslavie
info_indices[nrow(info_indices)+1,] <-  list("F","L'intervention infernale en Yougoslavie",1,"")
info_indices[nrow(info_indices)+1,] <-  list("F","L'intervention infernale en Yougoslavie",2,"Peu de temps avant la mort de Dieu, une immense armée de démons est intervenue en Yougoslavie, afin de détruire une parti de la population humaine présente là-bas. Ce qui est vraiment étrange, c'est que cette armée était dirigée par Lucifer en personne.
Normalement, jamais Lucifer n'intervient sur Terre, laissant ses démons ou Prince Démons le faire à sa place. Surtout que depuis quelques temps, il semble vouloir se retirer de son rôle de responsable de l'Enfer. Et Dieu, s'il était toujours là, n'apprécierait guère cette intervention.")
info_indices[nrow(info_indices)+1,] <-  list("F","L'intervention infernale en Yougoslavie",3,"Peu de temps avant la mort de Dieu, une immense armée de démons est intervenue en Yougoslavie, afin de détruire une parti de la population humaine présente là-bas. Les observateurs présents sur place ont noté que la population était atteint d'une sortie d'afflictions, les rendants particulièrement aggressifs envers tout le monde. Les forces de polices et d'armées locales étaient totalement débordées.

Par contre, ce qui est vraiment étrange, c'est que cette armée était dirigée par Lucifer en personne. Normalement, jamais Lucifer n'intervient sur Terre, laissant ses démons ou Prince Démons le faire à sa place. Surtout que depuis quelques temps, il semble vouloir se retirer de son rôle de responsable de l'Enfer. Et Dieu, s'il était toujours là, n'apprécierait guère cette intervention.")

# Un système de protection des Archanges
info_indices[nrow(info_indices)+1,] <-  list("G","Un système de protection des Archanges",1,"")
info_indices[nrow(info_indices)+1,] <-  list("G","Un système de protection des Archanges",2,"Après discussion avec Dieu, Yves (l'Archange des Sources) a conçu une protection divine pour toutes les entités divines. En cas de blessure mortelle, ils pourraient automatiquement être téléporté au Paradis, et ainsi être soigné. Pour l'instant, ce cercle de protection n'est valide que pour les Archanges, mais Yves espère poursuivre son travail et l'étendre aux anges.")
info_indices[nrow(info_indices)+1,] <-  list("G","Un système de protection des Archanges",3,"Après discussion avec Dieu, Yves (l'Archange des Sources) a conçu une protection divine pour toutes les entités divines. En cas de blessure mortelle, ils pourraient automatiquement être téléporté au Paradis, et ainsi être soigné. Pour l'instant, ce cercle de protection n'est valide que pour les Archanges, mais Yves espère poursuivre son travail et l'étendre aux anges. Dieu aurait choisi l'endroit d'arrivé de la téléportation : son laboratoire privé.
Note de l'équipe d'investigateurs :
L'endroit de la téléportation est exactement le lieu où Dieu partait dans les mondes parallèles, et surtout là où se trouve la fameuse manette. Nous ne savons pas s'il y a un lien, mais cette coïncidence est troublante.")

# Une rencontre entre Archange et Prince Démon sur Terre
info_indices[nrow(info_indices)+1,] <-  list("H","Une rencontre entre Archange et Prince Démon sur Terre",1,"")
info_indices[nrow(info_indices)+1,] <-  list("H","Une rencontre entre Archange et Prince Démon sur Terre",2,"Nous avons appris qu'une rencontre entre Kronos (Prince démon de l'Eternité), Blandine (Archange des Sources), un Archange et un Prince Démon (que nous n'avons pu identifié) a eu lieu au bar 'Chez Régis' (là où vous passez actuellement la soirée). C'est principalement Kronos qui parlait. Il expliquait que les voyages temporels sont totalement interdits, car ils risquent de modifier le continuum espace-temps. Blandin restait dans son coin et écoutait les intervenants. Les deux autres individus présents semblaient très intéressés par les aspects pratiques des voyages, et sur la détermination des dates et lieux durant un voyage.")
info_indices[nrow(info_indices)+1,] <-  list("H","Une rencontre entre Archange et Prince Démon sur Terre",3,"Nous avons appris qu'une rencontre entre Kronos (Prince démon de l'Eternité), Blandine (Archange des Sources), un Archange et un Prince Démon (que nous n'avons pu identifié) a eu lieu au bar 'Chez Régis' (là où vous passez actuellement la soirée). C'est principalement Kronos qui parlait. Il expliquait que les voyages temporels sont totalement interdits, car ils risquent de modifier le continuum espace-temps. Blandin restait dans son coin et écoutait les intervenants. Les deux autres individus présents semblaient très intéressés par les aspects pratiques des voyages, et sur la détermination des dates et lieux durant un voyage.
Une autre équipe est retournée sur place, et a utilisé des méthodes 'innovantes' pour faire parler Régis, le tavernier. Il expliqua que les deux autres individus étaient Crocell (Prince Démon du froid) et Janus (Archange des Vents).")

# Un vol chez l'archange Yves
info_indices[nrow(info_indices)+1,] <-  list("I","Un vol chez l'archange Yves",1,"Valefor, prince Démon des voleurs, aurait été vu à de nombreuses reprises entrain de visiter les grottes de Lascaux. Nous ne savons pas vous dire s'il aurait volé des oeuvres.")
info_indices[nrow(info_indices)+1,] <-  list("I","Un vol chez l'archange Yves",2,"Un objet magique très puissant aurait été volé il y a quelques semaines dans la bibliothèque d’Yves, Archange des Sources, au Paradis. Cet objet magique serait la clé (un exemplaire unique ouvrant les portes de l’escalier qui mène de l'Enfer au Paradis.

Remarques de votre chargé de mission :
Ce vol n’a pu être effectué que par un Ange ou un Archange. La bibliothèque d’Yves est en effet, au sein du Paradis, un endroit particulièrement bien gardé. La présence d’un Démon ou d’un Prince
Démon aurait fait résonner toutes les alarmes.")
info_indices[nrow(info_indices)+1,] <-  list("I","Un vol chez l'archange Yves",3,"Un objet magique très puissant aurait été volé il y a quelques semaines dans la bibliothèque d’Yves, Archange des Sources, au Paradis. Cet objet magique serait la clé (un exemplaire unique ouvrant les portes de l’escalier qui mène de l’Enfer au Paradis.

Remarques de votre chargé de mission :
Ce vol n’a pu être effectué que par un Ange ou un Archange. La bibliothèque d’Yves est en effet, au sein du Paradis, un endroit particulièrement bien gardé. La présence d’un Démon ou d’un Prince
Démon aurait fait résonner toutes les alarmes. Un Démon ou un Prince Démon en possession de cette clé pourrait entrera volonté au Paradis de manière discrète (du moins s’il éliminait les Anges gardiens qui  surveillent l’arrivée de l’escalier). Il aurait donc pu accéder à la tour d’argent ou Dieu faisait ses expériences et pousser la manette. Bien entendu, cette remarque est en contradiction avec la précédente... puisque seul un Ange ou un Archange a pu voler cette clé.")

# Apparition de l'Antéchrist
info_indices[nrow(info_indices)+1,] <-  list("J","Destruction du Vatican",1,"Au bar de la cafétéria de l’Enfer, 10 kilos de cacahuètes sont consommés quotidiennement.")
info_indices[nrow(info_indices)+1,] <-  list("J","Destruction du Vatican",2,"Les journaux d’Italie et les informations régionales de Rome ont annoncé, il y a environ trois semaines, l’apparition d’un être de flammes dans la basilique Saint Pierre, au cœur du Vatican. Cet être aurait commencé à ravager le Vatican, puis la ville... avant que l’apparition de deux autres êtres, un rougeoyant, un doré armé d’une épée, ait mis fin à ses exactions. Ces informations ont été diffusées pendant une journée sur les télévisions locales... Puis elles ont brusquement disparu des journaux et des écrans. Le lendemain, on a annoncé qu’il s’agissait d’un canular, et que les incendies qui ont ravagé une partie de la ville étaient dus à l’explosion inopinée d’une conduite de gaz.
Remarque de votre chargé de mission :
Ce brusque «secret défense» sur un incident qui, d’après des milliers de témoins, a véritablement eu lieu, est caractéristique d’une intervention des services de désinformation du Paradis ou de l’Enfer, voire des deux à la fois. Ceux-ci voulaient empêcher les humains d’en savoir trop sur cet événement. Selon toute logique, «l’être rougeoyant» devait être un Prince Démon, le «doré armé d’une épée» un Archange. Il semble que les deux se soient alliés pour combattre le mystérieux être de flamme.")
info_indices[nrow(info_indices)+1,] <-  list("J","Destruction du Vatican",3,"Les journaux d’Italie et les informations régionales de Rome ont annoncé, il y a environ trois semaines, l’apparition d’un être de flammes dans la basilique Saint Pierre, au cœur du Vatican. Cet être aurait annoncé être l’Antéchrist, et des milliers de témoins l’auraient vu faire preuve d’une puissance inimaginable. Puis cette créature monstrueuse aurait commencé à ravager le Vatican, puis Rome. Toujours d’après les témoins, deux autres êtres sont ensuite apparus : un immense colosse rougeoyant, avec des cornes et une armure d’écailles et une hache, et un grand homme brun à la peau dorée armé d’une gigantesque épée. Après un combat épique, les deux nouveaux arrivants ont détruit cet être de flammes qui se disait l’Antéchrist, sauvant ainsi la ville. L’information a été diffusée pendant une journée sur les télévisions locales... Puis les services de désinformation du Paradis et de l’Enfer sont entrés en jeu. Le lendemain, on a annoncé que cette histoire n’était qu’un gigantesque canular, et que les incendies et les morts étaient dus à l’explosion inopinée d’une conduite de gaz.
Remarque de votre chargé de mission :

D’après les descriptions que nous avons obtenues, il paraît presque certain que l’être rougeoyant à la hache était le Prince Démon Baal, et l’homme doré l'Archange Dominique. Il semble que les deux se soient alliés pour combattre le mystérieux être de flammes, dont l’origine demeure inconnue.")

# La fausse signature de Lucifer
info_indices[nrow(info_indices)+1,] <-  list("K","Problèmes administratifs en Enfer",1,"3592,4 cheeseburgers sont consommés quotidiennement à la cafétéria du Paradis. 25 sont volés.")
info_indices[nrow(info_indices)+1,] <-  list("K","Problèmes administratifs en Enfer",2,"Un scandale a secoué, il y a quinze jours, les services administratifs de l’Enfer. Il semble qu’un papier vierge orné de la signature de Lucifer ait été volé. Un individu non identifié se serait ensuite servi de ce parchemin en se faisant passer pour un envoyé de Lucifer auprès d’un Prince Démon (nous ne savons pas encore lequel). Grâce à ce parchemin, il aurait obtenu de ce Prince Démon une clé. La nature de cette clé reste inconnue.")
info_indices[nrow(info_indices)+1,] <-  list("K","Problèmes administratifs en Enfer",3,"Un scandale a secoué, il y a quinze jours, les services administratifs de l’Enfer. Il semble qu’un papier vierge orné de la signature de Lucifer ait été volé. Un individu non identifié se serait ensuite servi de ce parchemin en se faisant passer pour un envoyé de Lucifer auprès du Prince Démon Valefor. Grâce à ce parchemin, il aurait obtenu de Valefor une clé. La nature de cette clé reste inconnue.

Remarque de votre chargé de mission :
Une rumeur persistante, dont nous n’avons pas encore pu avoir confirmation, affirme que le Prince Démon Valefor aurait fait un double de cette clé avant de la donner a celui qu’il prenait pour un envoyé de Lucifer.")


# Ragots d'un petit démon
info_indices[nrow(info_indices)+1,] <-  list("L","Ragots d'un petit démon",1,"Le film «Les Ailes du Désir» sera projeté mardi 10 avril 1999, à 22H15, dans la salle B23 de la tour d’argent n°7 du Paradis. Il s’agit de la version japonaise sous-titrée en cantonais. Tous les Anges seront les bienvenus à cette projection exceptionnelle.")
info_indices[nrow(info_indices)+1,] <-  list("L","Ragots d'un petit démon",2,"Un Démon mineur dénommé Rakkâl a raconté partout à la cafétéria de l’Enfer qu’il avait des informations «croustillantes» et «inédites» à vendre sur les Archanges et les Princes Démons. Rakkâl s’occupa du ménage de beaucoup d’appartements de personnalités importantes de l’Enfer et affirme avoir ainsi appris des «scoops». Personne ne semble l’avoir pris au sérieux. Selon vos instructions, nous avons capturé Rakkâl et l’avons un peu secoué... Ces fameux «scoops» ne sont en vérité que deux. Les voici tels quels —nous ne pouvons hélas pas vous confirmer leur véracité :
- Rakkâl aurait aperçu en Enfer l’Archange Jésus (le fils de Dieu). Celui-là se serait déguisé en Prince Démon et se promènerait masqué. 
- Rakkâl affirme avoir trouvé dans les appartements du Prince Démon Crocell une lance d’aspect antique, dont la pointe était maculée de sang.")
info_indices[nrow(info_indices)+1,] <-  list("L","Ragots d'un petit démon",3,"Un Démon mineur dénommé Rakkâl a raconté partout à la cafétéria de l’Enfer qu’il avait des informations «croustillantes» et «inédites» à vendre sur les Archanges et les Princes Démons. Rakkâl s’occupe du ménage de beaucoup d’appartements de personnalités importantes de l’Enfer et affirme avoir ainsi appris des «scoops». Personne ne semble l’avoir pris au sérieux. Selon vos instructions, nous avons capturé Rakkâl et l’avons salement torturé jusqu’à ce qu’il nous dise tout, plus que tout et même le reste. Nous vous livrons ces «scoops» tels quels — nous ne pouvons hélas pas vous confirmer leur véracité :
- Rakkâl aurait aperçu en Enfer l’Archange Jésus (le fils de Dieu). Celui-ci se serait déguisé en Prince Démon et se promènerait masqué. Sous ce déguisement, il aurait eu de longues conversations scientifiques et techniques avec le Prince Démon Malphas et une troisième personne, que Rakkâl ne connaît pas
- Rakkâl affirme avoir trouvé dans les appartements du Prince Démon Crocell une lance d’aspect antique, dont la pointe était maculée de sang.
- Rakkâl affirme avoir vu le Prince Démon Valefor vendre une clé au Prince Démon Malphas.
- Rakkâl affirme avoir entendu le Prince Démon Andréalphus se vanter, un jour de cuite, d’être en train de mener une aventure sexuelle torride avec un Archange.

Remarque de votre chargé de mission :
À propos de ce dernier scoop... Ce ragot semble peu vraisemblable. Vous savez, Monseigneur, l’importance que Dieu porte à la chasteté de ces Archanges. Celui qui trahirait cette règle s'exposerait, ainsi que son complice, à de graves châtiments, voire à une annihilation totale.")

# Emploi du temps des archanges dossier C42
info_indices[nrow(info_indices)+1,] <-  list("M","Emploi du temps des archanges dossier C42",1,"Andromalius, Prince Démon du Jugement (non présent à cette soirée) aurait été vu dansant la gigue en kilt dans un mariage écossais.")
info_indices[nrow(info_indices)+1,] <-  list("M","Emploi du temps des archanges dossier C42",2,"Vous nous aviez demandé d’enquêter sur un dossier confidentiel de surveillance de l’emploi du temps des Archanges mené par les services d’espionnage du Paradis. Nous avons découvert le dossier auquel vous faites allusion. Il s’agit du dossier C-42, considéré comme brûlant et qui a été transmis au service d’information de Dieu. Nous ignorons encore si Dieu en avait ou non pris connaissance avant sa disparition.
Ce dossier, dont nous avons réussi à obtenir une copie, contenait deux rapports : un sur l'Archange Blandine (Blandin), Archange des Rêves et un sur l’Archange Janus, Archange des Vents.
- Le rapport sur Blandine (Blandin) affirme que l’Archange passe environ un tiers de son temps sur terre, sous forme humaine, pour des distractions personnelles. Blandine (Blandin) aurait en particulier passé beaucoup de temps ces derniers mois dans un petit hôtel italien, l’hôtel Ragazza à Milan. On ignore ce quelle (il) y faisait, mais les services d’espionages affirment qu’elle (il) n’était pas là-bas en mission officielle. Une enquête a été ouverte pour en savoir plus, mais celle-ci a été interrompue par la mort des Dieu.
- Le rapport sur Janus, Archange des Vents, a disparu du dossier. Nous vous confirmons cependant son existence. Les services d’espionnage du Paradis pensent qu’il a été volé.")
info_indices[nrow(info_indices)+1,] <-  list("M","Emploi du temps des archanges dossier C42",3,"Vous nous aviez demandé d’enquêter sur un dossier confidentiel de surveillance de l’emploi du temps des Archanges mené par les services d’espionnage du Paradis. Nous avons découvert le dossier auquel vous faites allusion. Il s’agit du dossier C-42, considéré comme brûlant et qui a été transmis au service d’information de Dieu. Nous ignorons encore si Dieu en avait ou non pris connaissance avant sa disparition. Ce dossier, dont nous avons réussi à obtenir une copie, contenait deux rapports : un sur l’Archange Blandine (Blandin), Archange des Rêves et un sur l’Archange Janus, Archange des Vents.
- Le rapport sur Blandine (Blandin) affirme quel l’Archange passe environ un tiers de son temps sur terre, sous forme humaine, pour des distractions personnelles. Blandine (Blandin) aurait en particulier passé beaucoup de temps ces derniers mois, incarnée dans un corps de femme, dans un petit hôtel italien (l’hôtel Ragazza à Milan). On ignore ce qu’«elle» y faisait, mais les services d’espionnages affirment qu’elle n’était pas là-bas en mission officielle. Une enquête a été ouverte pour en savoir plus, mais celle-ci a été interrompue par la mort de Dieu.
- Le rapport sur Janus, Archange des Vents, avait disparu du dossier. Les services d’espionnage du Paradis pensaient qu’il avait été volé. Nous avons, après de longues recherches, retrouvé sa trace en enfer, dans les appartements du Prince Démon Valefor (nous ignorons ce qu’il faisait là-bas). Le rapport affirme que Janus, Archange des Vents, ne passe qu’environ 50% de son temps à faire son travail d’Archange. Le reste du temps, il disparaît, purement et simplement. Une enquête a été ouverte pour en savoir plus, celle-ci a été interrompue par la mort de Dieu.
- Enfin, nous avons découvert un post-it accolé au dossier C-42. Il s’agit d’une petite note. Un témoin affirmerait avoir vu au paradis l’Archange Jésus, blessé à la poitrine et saignant abondamment, regagner à pied ses appartements... cela quelques minutes après la mort de Dieu.")

# Rapport de police, incident du bar dit « chez petit Louis »
info_indices[nrow(info_indices)+1,] <-  list("N","Rapport de police, incident du bar dit « chez petit Louis »",1,"Le Pape Jean-Paul II aurait été vu dans un bar branché ; il passait la soirée avec un Chippendale.")
info_indices[nrow(info_indices)+1,] <-  list("N","Rapport de police, incident du bar dit « chez petit Louis »",2,"Vous nous avez demandé de prendre connaissance du rapport de police relatant les événements s’étant déroulés le jour de la mort de Dieu, dans un bar appelé «Chez Petit Louis», en banlieue parisienne.
Nous avons obtenu copie de ce rapport. Il semble qu’un individu aux cheveux longs buvait tranquillement un canon quand un second individu est soudain apparu en plein milieu du bar, une sorte de pique à la main. Le nouvel arrivant s’est jeté sur le buveur et l’a transpercé de la fameuse pique. Puis tous deux ont disparu.")
info_indices[nrow(info_indices)+1,] <-  list("N","Rapport de police, incident du bar dit « chez petit Louis »",3,"Vous nous avez demandé de prendre connaissance du rapport de police relatant les événements s’étant déroulés le jour de la mort de Dieu, dans un bar appelé «Chez Petit Louis», en banlieue parisienne.
Nous avons obtenu copie de ce rapport. Il semble qu’un individu aux cheveux longs buvait tranquillement un canon quand un second individu est soudain apparu en plein milieu du bar, une sorte de pique à la main. Le nouvel arrivant s’est jeté sur le buveur et l’a transpercé de la fameuse pique.
D’après des témoins que nous avons interrogé pour compléter le rapport, le buveur a été blessé, sans doute gravement, à la poitrine ; il semblait très surpris. Son attaquant a alors levé son arme pour l’achever... le buveur, qui saignait abondamment, a alors disparu, évitant ainsi le deuxième assaut. L’individu à la pique a lui aussi disparu peu après, l’air déçu. Deux personnes au moins ont mentionné que la température avait brusquement baissé au moment de l’apparition de l’assaillant. «Il faisait vraiment très froid» ont-ils dit.
Remarques de votre chargé de mission :
Les apparitions et les disparitions soudaines de ces deux individus sont étranges — elles font pensera des pouvoirs d’Archange ou de Prince Démon. Permettez-nous d’ajouter, Monseigneur, que les combats entre Archanges et Princes Démons sont interdits par Dieu. S’il se révélait véridique que l’un d’eux (l’individu à la pique) avait transgressé cette règle, le châtiment prévu pourrait être terrible.")

# Rapport du démon Jukseksakj sur l'activité etherique anormale de l'hotel Ragazza à Milan
info_indices[nrow(info_indices)+1,] <-  list("O","Rapport du démon Jukseksakj sur l'activité etherique anormale de l'hotel Ragazza à Milan",1,"On raconte que Bill Clinton a des penchants pervers pour les kangourous asthmatiques.")
info_indices[nrow(info_indices)+1,] <-  list("O","Rapport du démon Jukseksakj sur l'activité etherique anormale de l'hotel Ragazza à Milan",2,"Le Démon Jukseksakj aurait fait parvenir il y a quelques semaines au Bureau des Affaires Spéciales de Lucifer un rapport sur une activité éthérique anormale à l’hôtel Raggaza à Milan. Dans cet hôtel se trouvait un couple illégitime (une femme et un homme) que les instruments ont rapidement désigné comme étant le centre de la perturbation. Cet homme et cette femme étaient engagés, semble-t-il, dans une aventure sexuelle... mais leur activité, bien que passionnée, n’explique évidemment pas le maëlstrom d’énergie recensé. Cette énergie était, d’après les analyses, ou Archangélique, ou Démoniaque, ou les deux à la fois. Elle a brusquement cessé trois semaines après avoir commencé, quand le couple s’est séparé.")
info_indices[nrow(info_indices)+1,] <-  list("O","Rapport du démon Jukseksakj sur l'activité etherique anormale de l'hotel Ragazza à Milan",3,"Le Démon Jukseksakj a fait parvenir il y a quelques semaines au Bureau des Affaires Spéciales de Lucifer un rapport sur une activité éthérique anormale à l’hôtel Raggaza, à Milan. Dans cet hôtel se trouvait un couple illégitime (une femme et un homme) que les instruments ont rapidement désigné comme étant le centre de la perturbation. Cet homme et cette femme étaient engagés, semble-t-il, dans une aventure sexuelle... mais leur activité, bien que passionnée, n’explique pas en elle-même le maëlstrom d’énergie recensé. Il semble évident, d’après les analyses plus poussées, qu’un des deux partenaires était un Prince Démon, l’autre un Archange. Le «choc» des énergies angéliques et démoniaques ont créé la perturbation recensée. L'énergie a brusquement cessé trois semaines après avoir commencé, quand le couple s’est séparé.
Remarque de votre chargé de mission:
Les résultats de cette enquête sont étonnants... et explosifs. Vous savez, Monseigneur, l’importance que Dieu porte a la chasteté de ses Archanges. Celui qui trahirait cette règle s’exposerait, ainsi que son complice, à de graves châtiments, voire a une annihilation totale.")


# L’incident de l’escalier
info_indices[nrow(info_indices)+1,] <-  list("P","L’incident de l’escalier",1,"Daniel, Archange de la Pierre, non présent à cette soirée, aurait introduit en fraude au Paradis 5000 canettes de Heineken.")
info_indices[nrow(info_indices)+1,] <-  list("P","L’incident de l’escalier",2,"D’après le journal de bord de l’Ange Melchior, un incident étonnant est advenu le jour de la mort de Dieu. Deux Anges dont le rôle était de garder l’arrivée de l’escalier qui mène de l’Enfer au Paradis ont été attaqués par surprise — en plein Paradis, donc - par un être rougeoyant et écailleux qui s’est rapidement débarrassé d’eux. L’être a ensuite disparu entre les tours d’argent. Les Anges, honteux de leur défaite et de leur manque de vigilance, ont semble-t-il dissimulé cet incident aux autorités compétentes.")
info_indices[nrow(info_indices)+1,] <-  list("P","L’incident de l’escalier",3,"D’après le journal de bord de l’Ange Melchior, un incident étonnant est advenu le jour de la mort de Dieu. Deux anges dont le rôle était de garder l’arrivée des l’escalier qui mène de l’Enfer au Paradis ont été attaqués par surprise — en plein Paradis, donc — par un être rougeoyant, écailleux, armé d’une hache, qui s’est rapidement débarrassé d’eux. L’être a ensuite disparu entre les tours d’argent. Les Anges, honteux de leur défaite et de leur manque de vigilance, ont semble-t-il dissimulé cet incident aux autorités compétentes. Il faut dire, à leur décharge, que cet escalier est supposé être fermé et que seul l’Archange Yves en possède la clé.")

# Des remous en enfer : conscription et entrainement
info_indices[nrow(info_indices)+1,] <-  list("Q","Des remous en enfer : conscription et entrainement",1,"Le Prince Démon Bélial a reçu officiellement un blâme de Lucifer pour avoir fait brûler toute la réserve de boudin créole de la cafétéria.")
info_indices[nrow(info_indices)+1,] <-  list("Q","Des remous en enfer : conscription et entrainement",2,"De nombreux témoins ont remarqué, ces dernières semaines, une certaine agitation des Démons travaillant pour le Prince Démon Baal. Conscription, entrainement, celui-ci a, semble-t-il, fait préparer ses troupes pour une offensive massive – contre quoi, nous l’ignorons. Les meilleurs éléments de tout l’Enfer, les plus dangereux, les plus violents ont été recrutés.
Puis, alors que tout était prêt, une demande inopinée de Lucifer qui avait besoin d’une escorte pour se rendre en Yougoslavie a obligé à annuler l’attaque.")
info_indices[nrow(info_indices)+1,] <-  list("Q","Des remous en enfer : conscription et entrainement",3,"De nombreux témoins ont remarqué, ces dernières semaines, une certaine agitation des Démons travaillant pour le Prince Démon Baal. Conscription, entraînement, celui-ci a, semble-t-il, fait préparer ses troupes pour une offensive massive — contre quoi, nous l’ignorons. Les meilleurs éléments de tout l’Enfer, les plus dangereux, les plus violents, ont été recrutés. Tous les Démons concernés ont fait remarquer que le Prince Démon Baal était très excité par contre quoi, nous l’attaque prévue, affirmant que ce serait la plus belle guerre jamais connue depuis la création de l’univers.
Certains ont affirmé avoir vu briller autour de son cou, comme un porte-bonheur, une clé.
Puis, alors que tout était prêt, une demande inopinée de Lucifer qui avait besoin d’une escorte pour se rendre en Yougoslavie a obligé à annuler l’attaque.")

# Le dossier Pélican
info_indices[nrow(info_indices)+1,] <-  list("R","Le dossier Pélican",1,"II y avait le 23 décembre 1995, 353 459 Démons en Enfer.")
info_indices[nrow(info_indices)+1,] <-  list("R","Le dossier Pélican",2,"Une rumeur court au Paradis à propos d’une enquête maudite, une enquête brûlante qui n’irait jamais jusqu’au bout parce que tous les papiers, les rapports, les documents se feraient régulièrement voler. Les services d’espionnage du Paradis ont surnommé cette affaire maudite : l’affaire Pélican. Il semble que tout vienne d’une théorie fumeuse, émise par un Ange obscur, qui a affirmé un jour avoir les preuves qu’un Archange et un Prince Démon étaient en vérité la même personne. Cette affirmation incroyable n’a malheureusement pas pu être étayée : toutes les preuves, s’il y en avait, ont été elles aussi volées...")
info_indices[nrow(info_indices)+1,] <-  list("R","Le dossier Pélican",3,"Une rumeur court au Paradis à propos d’une enquête maudite, une enquête brûlante qui n’irait jamais jusqu’au bout parce que tous les papiers, les rapports, les documents se feraient régulièrement voler. Les services d’espionnage du Paradis ont surnommé cette affaire maudite : l’affaire Pélican. Il semble que tout vienne d’une théorie fumeuse, émise par un Ange obscur, qui a affirmé un jour avoir les preuves que Janus, Archange des Vents, était en vérité un Prince Démon ! Cette affirmation incroyable n’a malheureusement pas pu être étayée : toutes les preuves, s’il y en avait, ont été elles aussi volées...")

# Un Jogging Rose de trop
info_indices[nrow(info_indices)+1,] <-  list("S","Un nouveau texte évangélique",1,"On raconte qu’un dossier secret des archives du Paradis ferait état de 569 naissances d’enfants de parents mixtes Anges-Démons pour le seul XXème siècle.")
info_indices[nrow(info_indices)+1,] <-  list("S","Un nouveau texte évangélique",2,"La découverte d’un texte évangélique inédit a mis la stupéfaction dans les hautes instances du Paradis. Le texte, en hébreu ancien, qui a été identifié comme authentique, narre un incident arrivé en 33, pendant la crucifixion de Jésus. Il semble qu’un individu en costume rose soit soudainement apparu du néant près des légionnaires romains et ait arraché à l’un d’entre eux la lance avec laquelle il venait de frapper Jésus sous la côte ! Cet être bizarre a ensuite disparu avec la lance, repartant dans le néant d’où il venait de sortir.")
info_indices[nrow(info_indices)+1,] <-  list("S","Un nouveau texte évangélique",3,"La découverte d’un texte évangélique inédit a mis la stupéfaction dans les hautes instances du Paradis.
Le texte, en hébreu ancien, qui a été identifié comme authentique, narre un incident arrivé en 33, pendant la crucifixion de Jésus. Il semble qu’un individu en costume rose soit soudainement apparu dui néant près des légionnaires romains et ait arraché à l’un d’entre eux la lance avec laquelle il venait de frapper Jésus sous la côte ! Cet être bizarre a ensuite disparu avec la lance, repartant dans le néant d’où il venait de sortir. Cette lance qui a blessé Jésus serait, d après la légende, une des seules armes ayant le pouvoir de frapper le fils de Dieu. Elle aurait été créée par Lucifer.")

